name = "solver"
uuid = "5b87f58b-a6cb-43fc-b459-8e7b9fbb6b24"
authors = ["Andrey Zakharevich <andreyzakharevich@gmail.com>"]
julia_version = "1.10"
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
NDPriorityQueues = "62ce6dcf-afc2-4b9e-bf6a-7a1353c578d1"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Redis = "0cf705f9-a9e2-50d1-a699-2b372a39b750"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SharedMemoryLocks = "7bb51ff7-3c6a-41be-b642-de78e6952b49"
StitchBindings = "98c25cc8-eb50-4420-96bf-d3053e46f68d"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
XUnit = "3e3c03f2-1a94-11e9-2981-050a4ca824ab"

[targets]
test = ["Test", "XUnit", "Aqua"]
